name: Release

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: yojigenserver/anytype

on:
  push:
    tags:
    - v*

jobs:
  release:
      runs-on: ubuntu-latest
      
      permissions:
        contents: read
        packages: write
        
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
            submodules: recursive
  
        - name: Login to GitHub Container Registry
          if: github.event_name != 'pull_request'
          uses: docker/login-action@v2
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: 'Build Image'
          run: |
            TAG=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            ANYTYPE_VERSION=$(git describe --tags | sed 's/^v//')
            VERSION=$(git describe --tags | sed 's/^v//')
            docker build . --build-arg ANYTYPE_VERSION=$ANYTYPE_VERSION -t $TAG:latest
            docker push $TAG:latest
            docker build . --build-arg ANYTYPE_VERSION=$ANYTYPE_VERSION -t $TAG:$VERSION
            docker push $TAG:$VERSION
            VERSION=$(echo "$VERSION" | cut -d "." -f 1,2)
            docker build . --build-arg ANYTYPE_VERSION=$ANYTYPE_VERSION -t $TAG:$VERSION
            docker push $TAG:$VERSION
